backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "restaurantMenu"
    label: "Menu Sections"
    folder: "content/restaurantMenu"
    create: true
    editor:
     preview: false
    fields:
      - label: "Section Name"
        name: "title"
        widget: "string"
      - label: "List"
        name: "list"
        widget: "list"
        fields:
          - {label: "Menu Item", name: "menuItem", widget: "string"}
          - {label: "Description", name: "menuItemDescription", widget: "string"}
          - {label: "Image", name: "menuItemImage", widget: "image"}
  - name: "siteConfig"
    label: "Site Config"
    files:
      - label: "Layout Editor"
        name: "layoutEditor"
        file: "content/siteEditor.json"
        fields:
        - label: "Top View Layout"
          name: "heroLayout"
          widget: "select"
          options: ["Left", "Center"]
          default: ["Left"]
        - label: "Restaurant Name"
          name: "restaurantName"
          widget: "string"
        - label: "Restaurant Tagline/Motto"
          name: "restaurantMotto"
          widget: "string"
          required: false
        - label: "Monday Hours"
          name: "mondayHours"
          allow_add: false
          fields:
            - {label: "Open", name: "mondayOpen", widget: "number"}
            - {label: "Close", name: "mondayOpen", widget: "number"}
        - label: "Tuesday Hours"
          name: "tuesdayHours"
          allow_add: false
          fields:
            - {label: "Open", name: "TuesdayOpen", widget: "number"}
            - {label: "Close", name: "TuesdayOpen", widget: "number"}
        - label: "Wednesday Hours"
          name: "wednesdayHours"
          allow_add: false
          fields:
            - {label: "Open", name: "wednesdayOpen", widget: "number"}
            - {label: "Close", name: "wednesdayOpen", widget: "number"}
        - label: "Thursday Hours"
          name: "thursdayHours"
          allow_add: false
          fields:
            - {label: "Open", name: "thursdayOpen", widget: "number"}
            - {label: "Close", name: "thursdayOpen", widget: "number"}
        - label: "Friday Hours"
          name: "fridayHours"
          allow_add: false
          fields:
            - {label: "Open", name: "fridayOpen", widget: "number"}
            - {label: "Close", name: "fridayOpen", widget: "number"}
        - label: "Saturday Hours"
          name: "saturdayHours"
          allow_add: false
          fields:
            - {label: "Open", name: "saturdayOpen", widget: "number"}
            - {label: "Close", name: "saturdayOpen", widget: "number"}
        - label: "Sunday Hours"
          name: "sundayHours"
          allow_add: false
          fields:
            - {label: "Open", name: "sundayOpen", widget: "number"}
            - {label: "Close", name: "sundayOpen", widget: "number"}
