backend:
  name: git-gateway
  branch: master

local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: "restaurantMenu"
    label: "Menu Sections"
    description: "This collection is a list of your menu's sections. In each section, you can list your items with a description and an optional image. Please note that the sections will not show up on your website in the same order that they are shown here. If you would like them to show up in a specific order, edit the 'Position In Menu List' field of the section."
    folder: "content/restaurantMenu"
    slug: "{{sectionTitle}}"
    create: true
    editor:
     preview: false
    fields:
      - label: "Section Name"
        name: "sectionTitle"
        widget: "string"
      - label: "Position in Menu List"
        name: "orderPosition"
        widget: "number"
        hint: "This number will determine the order of your menus' sections. First section is 1, second is 2, third is 3..."
      - label: "Item List"
        name: "menuSectionList"
        widget: "list"
        fields:
          - label: "Menu Item Title"
            name: "menuItem"
            widget: "string"
          - label: "Price"
            name: "menuItemPrice"
            widget: "number"
            valueType: "float"
          - label: "Favorite? (Gives this item a star in the menu!)"
            name: favorite
            widget: "boolean"
            default: false
          - label: "Description"
            name: "menuItemDescription"
            widget: "text"
          - label: "Image"
            name: "menuItemImage"
            widget: "image"
            required: false
          - label: "Order Options"
            name: "orderOptions"
            widget: "list"
            hint: "This list will show up for this item as the toppings, sauces, etc. in your ordering app!"
            fields:
              - {label: "Name", name: "orderOptionName", widget: "string"}
              - {label: "Price Change", name: "orderOptionPriceChange", required: false, widget: "number", valueType: "float", min: 0, default: 0, step: .25, hint: "Be careful! This number is a dollar amount! If left empty or zero, we won't show a price change for this option."}
  - name: "restaurantSpecials"
    label: "Restaurant Specials"
    description: "Here you can list some of your specials. Give your special a 'title' and a 'description' that makes it easily identifiable when someone calls in their order and says 'I'll take the 'two for twenty' that it says on the website.'"
    folder: "content/restaurantSpecials"
    slug: "{{specialTitle}}"
    create: true
    editor:
     preview: false
    fields:
      - label: "Special Title"
        name: "specialTitle"
        widget: "string"
      - label: "Special Subtitle"
        name: "specialSubtitle"
        widget: "string"
        required: false
      - label: "Description"
        name: "specialDescription"
        widget: "text"
  - name: "siteConfig"
    label: "Restaurant Information"
    editor:
      preview: false
    files:
      - label: "Restaurant Basic Info"
        name: "restaurantInfo"
        file: "content/restaurantInfo/restaurantBasicInfo.json"
        media_folder: "/static/assets"
        public_folder: "/static/assets"
        fields:
        - label: "Restaurant Name"
          name: "restaurantName"
          widget: "string"
        - label: "Restaurant Logo"
          name: "logo"
          widget: "image"
        - label: "Cover Image"
          name: "hero"
          widget: "image"
        - label: "Restaurant Tagline/Motto"
          name: "restaurantMotto"
          widget: "string"
          required: false
        - label: "Phone Number"
          name: "phone"
          widget: "string"
          hint: "Enter your phone number formatted EXACTLY how you want it to display on your site. (i.e. (555) 555-555 or 555-555-555)"
        - label: "Company Email"
          name: "email"
          widget: "string"
          hint: "If you'd like a custom email address with your site's domain, send an email to anthony@shewperman.dev."
          required: false
        - label: "Address"
          name: "address"
          widget: "object"
          fields:
            - {label: "Street Address", name: "streetAddress", widget: "string"}
            - {label: "City", name: "city", widget: "string"}
            - {label: "State", name: "state", widget: "select", options: ["AL", "AK", "AS", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FM", "FL", "GA", "GU", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MH", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "MP", "OH", "OK", "OR", "PW", "PA", "PR", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VI", "VA", "WA", "WV", "WI", "WY"]}
            - {label: "Zip Code", name: "zipCode", widget: "number"}
        - label: "About Us"
          name: "restaurantAbout"
          widget: text
          required: false
          hint: "If you leave this blank, the \"About Us\" will disappear from your site's page. Fill it in and you will have a section with your company story on your page!"
        - label: "Monday Hours"
          name: "mondayHours"
          widget: "object"
          hint: "To show that you are closed on this day, enter the same time in both boxes!"
          fields:
            - label: "Open"
              name: "open"
              widget: "select"
              options: ["12 AM", "12:30 AM", "1 AM", "1:30 AM", "2 AM", "2:30 AM", "3 AM", "3:30 AM", "4 AM", "4:30 AM", "5 AM", "5:30 AM", "6 AM", "6:30AM", "7 AM", "7:30 AM", "8 AM", "8:30 AM", "9 AM", "9:30 AM", "10 AM", "10:30 AM", "11 AM", "11:30 AM", "12 PM", "12:30 PM", "1 PM", "1:30 PM", "2 PM", "2:30 PM", "3 PM", "3:30 PM", "4 PM", "4:30 PM", "5 PM", "5:30 PM", "6 PM", "6:30 PM", "7 PM", "7:30 PM", "8 PM", "8:30 PM", "9 PM", "9:30 PM", "10 PM", "10:30 PM", "11 PM", "11:30 PM"]
            - label: "Close"
              name: "close"
              widget: "select"
              options: ["12 AM", "12:30 AM", "1 AM", "1:30 AM", "2 AM", "2:30 AM", "3 AM", "3:30 AM", "4 AM", "4:30 AM", "5 AM", "5:30 AM", "6 AM", "6:30AM", "7 AM", "7:30 AM", "8 AM", "8:30 AM", "9 AM", "9:30 AM", "10 AM", "10:30 AM", "11 AM", "11:30 AM", "12 PM", "12:30 PM", "1 PM", "1:30 PM", "2 PM", "2:30 PM", "3 PM", "3:30 PM", "4 PM", "4:30 PM", "5 PM", "5:30 PM", "6 PM", "6:30 PM", "7 PM", "7:30 PM", "8 PM", "8:30 PM", "9 PM", "9:30 PM", "10 PM", "10:30 PM", "11 PM", "11:30 PM"]
        - label: "Tuesday Hours"
          name: "tuesdayHours"
          widget: "object"
          hint: "To show that you are closed on this day, enter the same time in both boxes!"
          fields:
            - label: "Open"
              name: "open"
              widget: "select"
              options: ["12 AM", "12:30 AM", "1 AM", "1:30 AM", "2 AM", "2:30 AM", "3 AM", "3:30 AM", "4 AM", "4:30 AM", "5 AM", "5:30 AM", "6 AM", "6:30AM", "7 AM", "7:30 AM", "8 AM", "8:30 AM", "9 AM", "9:30 AM", "10 AM", "10:30 AM", "11 AM", "11:30 AM", "12 PM", "12:30 PM", "1 PM", "1:30 PM", "2 PM", "2:30 PM", "3 PM", "3:30 PM", "4 PM", "4:30 PM", "5 PM", "5:30 PM", "6 PM", "6:30 PM", "7 PM", "7:30 PM", "8 PM", "8:30 PM", "9 PM", "9:30 PM", "10 PM", "10:30 PM", "11 PM", "11:30 PM"]
            - label: "Close"
              name: "close"
              widget: "select"
              options: ["12 AM", "12:30 AM", "1 AM", "1:30 AM", "2 AM", "2:30 AM", "3 AM", "3:30 AM", "4 AM", "4:30 AM", "5 AM", "5:30 AM", "6 AM", "6:30AM", "7 AM", "7:30 AM", "8 AM", "8:30 AM", "9 AM", "9:30 AM", "10 AM", "10:30 AM", "11 AM", "11:30 AM", "12 PM", "12:30 PM", "1 PM", "1:30 PM", "2 PM", "2:30 PM", "3 PM", "3:30 PM", "4 PM", "4:30 PM", "5 PM", "5:30 PM", "6 PM", "6:30 PM", "7 PM", "7:30 PM", "8 PM", "8:30 PM", "9 PM", "9:30 PM", "10 PM", "10:30 PM", "11 PM", "11:30 PM"]
        - label: "Wednesday Hours"
          name: "wednesdayHours"
          widget: "object"
          hint: "To show that you are closed on this day, enter the same time in both boxes!"
          fields:
            - label: "Open"
              name: "open"
              widget: "select"
              options: ["12 AM", "12:30 AM", "1 AM", "1:30 AM", "2 AM", "2:30 AM", "3 AM", "3:30 AM", "4 AM", "4:30 AM", "5 AM", "5:30 AM", "6 AM", "6:30AM", "7 AM", "7:30 AM", "8 AM", "8:30 AM", "9 AM", "9:30 AM", "10 AM", "10:30 AM", "11 AM", "11:30 AM", "12 PM", "12:30 PM", "1 PM", "1:30 PM", "2 PM", "2:30 PM", "3 PM", "3:30 PM", "4 PM", "4:30 PM", "5 PM", "5:30 PM", "6 PM", "6:30 PM", "7 PM", "7:30 PM", "8 PM", "8:30 PM", "9 PM", "9:30 PM", "10 PM", "10:30 PM", "11 PM", "11:30 PM"]
            - label: "Close"
              name: "close"
              widget: "select"
              options: ["12 AM", "12:30 AM", "1 AM", "1:30 AM", "2 AM", "2:30 AM", "3 AM", "3:30 AM", "4 AM", "4:30 AM", "5 AM", "5:30 AM", "6 AM", "6:30AM", "7 AM", "7:30 AM", "8 AM", "8:30 AM", "9 AM", "9:30 AM", "10 AM", "10:30 AM", "11 AM", "11:30 AM", "12 PM", "12:30 PM", "1 PM", "1:30 PM", "2 PM", "2:30 PM", "3 PM", "3:30 PM", "4 PM", "4:30 PM", "5 PM", "5:30 PM", "6 PM", "6:30 PM", "7 PM", "7:30 PM", "8 PM", "8:30 PM", "9 PM", "9:30 PM", "10 PM", "10:30 PM", "11 PM", "11:30 PM"]
        - label: "Thursday Hours"
          name: "thursdayHours"
          widget: "object"
          hint: "To show that you are closed on this day, enter the same time in both boxes!"
          fields:
            - label: "Open"
              name: "open"
              widget: "select"
              options: ["12 AM", "12:30 AM", "1 AM", "1:30 AM", "2 AM", "2:30 AM", "3 AM", "3:30 AM", "4 AM", "4:30 AM", "5 AM", "5:30 AM", "6 AM", "6:30AM", "7 AM", "7:30 AM", "8 AM", "8:30 AM", "9 AM", "9:30 AM", "10 AM", "10:30 AM", "11 AM", "11:30 AM", "12 PM", "12:30 PM", "1 PM", "1:30 PM", "2 PM", "2:30 PM", "3 PM", "3:30 PM", "4 PM", "4:30 PM", "5 PM", "5:30 PM", "6 PM", "6:30 PM", "7 PM", "7:30 PM", "8 PM", "8:30 PM", "9 PM", "9:30 PM", "10 PM", "10:30 PM", "11 PM", "11:30 PM"]
            - label: "Close"
              name: "close"
              widget: "select"
              options: ["12 AM", "12:30 AM", "1 AM", "1:30 AM", "2 AM", "2:30 AM", "3 AM", "3:30 AM", "4 AM", "4:30 AM", "5 AM", "5:30 AM", "6 AM", "6:30AM", "7 AM", "7:30 AM", "8 AM", "8:30 AM", "9 AM", "9:30 AM", "10 AM", "10:30 AM", "11 AM", "11:30 AM", "12 PM", "12:30 PM", "1 PM", "1:30 PM", "2 PM", "2:30 PM", "3 PM", "3:30 PM", "4 PM", "4:30 PM", "5 PM", "5:30 PM", "6 PM", "6:30 PM", "7 PM", "7:30 PM", "8 PM", "8:30 PM", "9 PM", "9:30 PM", "10 PM", "10:30 PM", "11 PM", "11:30 PM"]
        - label: "Friday Hours"
          name: "fridayHours"
          widget: "object"
          hint: "To show that you are closed on this day, enter the same time in both boxes!"
          fields:
            - label: "Open"
              name: "open"
              widget: "select"
              options: ["12 AM", "12:30 AM", "1 AM", "1:30 AM", "2 AM", "2:30 AM", "3 AM", "3:30 AM", "4 AM", "4:30 AM", "5 AM", "5:30 AM", "6 AM", "6:30AM", "7 AM", "7:30 AM", "8 AM", "8:30 AM", "9 AM", "9:30 AM", "10 AM", "10:30 AM", "11 AM", "11:30 AM", "12 PM", "12:30 PM", "1 PM", "1:30 PM", "2 PM", "2:30 PM", "3 PM", "3:30 PM", "4 PM", "4:30 PM", "5 PM", "5:30 PM", "6 PM", "6:30 PM", "7 PM", "7:30 PM", "8 PM", "8:30 PM", "9 PM", "9:30 PM", "10 PM", "10:30 PM", "11 PM", "11:30 PM"]
            - label: "Close"
              name: "close"
              widget: "select"
              options: ["12 AM", "12:30 AM", "1 AM", "1:30 AM", "2 AM", "2:30 AM", "3 AM", "3:30 AM", "4 AM", "4:30 AM", "5 AM", "5:30 AM", "6 AM", "6:30AM", "7 AM", "7:30 AM", "8 AM", "8:30 AM", "9 AM", "9:30 AM", "10 AM", "10:30 AM", "11 AM", "11:30 AM", "12 PM", "12:30 PM", "1 PM", "1:30 PM", "2 PM", "2:30 PM", "3 PM", "3:30 PM", "4 PM", "4:30 PM", "5 PM", "5:30 PM", "6 PM", "6:30 PM", "7 PM", "7:30 PM", "8 PM", "8:30 PM", "9 PM", "9:30 PM", "10 PM", "10:30 PM", "11 PM", "11:30 PM"]
        - label: "Saturday Hours"
          name: "saturdayHours"
          widget: "object"
          hint: "To show that you are closed on this day, enter the same time in both boxes!"
          fields:
            - label: "Open"
              name: "open"
              widget: "select"
              options: ["12 AM", "12:30 AM", "1 AM", "1:30 AM", "2 AM", "2:30 AM", "3 AM", "3:30 AM", "4 AM", "4:30 AM", "5 AM", "5:30 AM", "6 AM", "6:30AM", "7 AM", "7:30 AM", "8 AM", "8:30 AM", "9 AM", "9:30 AM", "10 AM", "10:30 AM", "11 AM", "11:30 AM", "12 PM", "12:30 PM", "1 PM", "1:30 PM", "2 PM", "2:30 PM", "3 PM", "3:30 PM", "4 PM", "4:30 PM", "5 PM", "5:30 PM", "6 PM", "6:30 PM", "7 PM", "7:30 PM", "8 PM", "8:30 PM", "9 PM", "9:30 PM", "10 PM", "10:30 PM", "11 PM", "11:30 PM"]
            - label: "Close"
              name: "close"
              widget: "select"
              options: ["12 AM", "12:30 AM", "1 AM", "1:30 AM", "2 AM", "2:30 AM", "3 AM", "3:30 AM", "4 AM", "4:30 AM", "5 AM", "5:30 AM", "6 AM", "6:30AM", "7 AM", "7:30 AM", "8 AM", "8:30 AM", "9 AM", "9:30 AM", "10 AM", "10:30 AM", "11 AM", "11:30 AM", "12 PM", "12:30 PM", "1 PM", "1:30 PM", "2 PM", "2:30 PM", "3 PM", "3:30 PM", "4 PM", "4:30 PM", "5 PM", "5:30 PM", "6 PM", "6:30 PM", "7 PM", "7:30 PM", "8 PM", "8:30 PM", "9 PM", "9:30 PM", "10 PM", "10:30 PM", "11 PM", "11:30 PM"]
        - label: "Sunday Hours"
          name: "sundayHours"
          widget: "object"
          hint: "To show that you are closed on this day, enter the same time in both boxes!"
          fields:
            - label: "Open"
              name: "open"
              widget: "select"
              options: ["12 AM", "12:30 AM", "1 AM", "1:30 AM", "2 AM", "2:30 AM", "3 AM", "3:30 AM", "4 AM", "4:30 AM", "5 AM", "5:30 AM", "6 AM", "6:30AM", "7 AM", "7:30 AM", "8 AM", "8:30 AM", "9 AM", "9:30 AM", "10 AM", "10:30 AM", "11 AM", "11:30 AM", "12 PM", "12:30 PM", "1 PM", "1:30 PM", "2 PM", "2:30 PM", "3 PM", "3:30 PM", "4 PM", "4:30 PM", "5 PM", "5:30 PM", "6 PM", "6:30 PM", "7 PM", "7:30 PM", "8 PM", "8:30 PM", "9 PM", "9:30 PM", "10 PM", "10:30 PM", "11 PM", "11:30 PM"]
            - label: "Close"
              name: "close"
              widget: "select"
              options: ["12 AM", "12:30 AM", "1 AM", "1:30 AM", "2 AM", "2:30 AM", "3 AM", "3:30 AM", "4 AM", "4:30 AM", "5 AM", "5:30 AM", "6 AM", "6:30AM", "7 AM", "7:30 AM", "8 AM", "8:30 AM", "9 AM", "9:30 AM", "10 AM", "10:30 AM", "11 AM", "11:30 AM", "12 PM", "12:30 PM", "1 PM", "1:30 PM", "2 PM", "2:30 PM", "3 PM", "3:30 PM", "4 PM", "4:30 PM", "5 PM", "5:30 PM", "6 PM", "6:30 PM", "7 PM", "7:30 PM", "8 PM", "8:30 PM", "9 PM", "9:30 PM", "10 PM", "10:30 PM", "11 PM", "11:30 PM"]
      - label: "Online Ordering Settings"
        name: "orderingSettings"
        file: "content/restaurantInfo/orderingSettings.json"
        fields:
        - label: "Online Ordering Available?"
          name: "orderingBool"
          widget: "boolean"
          default: false
          hint: "Turn this switch on if you would like online ordering to be available!"
        - label: "Takeout Delay"
          name: "takeoutDelay"
          widget: "number"
          hint: "The amount of time we will tell your customers to expect their food in."
