backend:
  name: git-gateway
  branch: master

local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: "restaurantMenu"
    label: "Menu Sections"
    folder: "content/restaurantMenu"
    create: true
    editor:
     preview: false
    fields:
      - label: "Section Name"
        name: "title"
        widget: "string"
      - label: "List"
        name: "list"
        widget: "list"
        fields:
          - {label: "Menu Item", name: "menuItem", widget: "string"}
          - {label: "Description", name: "menuItemDescription", widget: "string"}
          - {label: "Image", name: "menuItemImage", widget: "image"}
  - name: "siteConfig"
    label: "Site Config"
    files:
      - label: "Restaurant Info"
        name: "restaurantInfo"
        file: "content/restaurantInfo.json"
        fields:
        - label: "Restaurant Name"
          name: "restaurantName"
          widget: "string"
        - label: "Restaurant Tagline/Motto"
          name: "restaurantMotto"
          widget: "string"
          required: false
        - label: "Monday Hours"
          name: "mondayHours"
          widget: "object"
          fields:
            - label: "Open"
              name: "mondayOpen"
              widget: "object"
              fields:
              - {label: "Hour", name: "mondayHourOpen", widget: "number"}
              - {label: "AM/PM", name: "mondayHalfOpen", widget: "select", options: ["AM", "PM"], default: ["AM"]}
            - label: "Close"
              name: "mondayClose"
              widget: "object"
              fields:
              - {label: "Hour", name: "mondayHourClose", widget: "number"}
              - {label: "AM/PM", name: "mondayHalfClose", widget: "select", options: ["AM", "PM"], default: ["PM"]}
        - label: "Tuesday Hours"
          name: "tuesdayHours"
          allow_add: false
          widget: "object"
          fields:
            - label: "Open"
              name: "tuesdayOpen"
              widget: "object"
              fields:
              - {label: "Hour", name: "tuesdayHourOpen", widget: "number"}
              - {label: "AM/PM", name: "tuesdayHalfOpen", widget: "select", options: ["AM", "PM"], default: ["AM"]}
            - label: "Close"
              name: "tuesdayClose"
              widget: "object"
              fields:
              - {label: "Hour", name: "tuesdayHourClose", widget: "number"}
              - {label: "AM/PM", name: "tuesdayHalfClose", widget: "select", options: ["AM", "PM"], default: ["PM"]}
        - label: "Wednesday Hours"
          name: "wednesdayHours"
          allow_add: false
          widget: "object"
          fields:
            - label: "Open"
              name: "wednesdayOpen"
              widget: "object"
              fields:
              - {label: "Hour", name: "wednesdayHourOpen", widget: "number"}
              - {label: "AM/PM", name: "wednesdayHalfOpen", widget: "select", options: ["AM", "PM"], default: ["AM"]}
            - label: "Close"
              name: "wednesdayClose"
              widget: "object"
              fields:
              - {label: "Hour", name: "wednesdayHourClose", widget: "number"}
              - {label: "AM/PM", name: "wednesdayHalfClose", widget: "select", options: ["AM", "PM"], default: ["PM"]}
        - label: "Thursday Hours"
          name: "thursdayHours"
          allow_add: false
          widget: "object"
          fields:
            - label: "Open"
              name: "thursdayOpen"
              widget: "object"
              fields:
              - {label: "Hour", name: "thursdayHourOpen", widget: "number"}
              - {label: "AM/PM", name: "thursdayHalfOpen", widget: "select", options: ["AM", "PM"], default: ["AM"]}
            - label: "Close"
              name: "thursdayClose"
              widget: "object"
              fields:
              - {label: "Hour", name: "thursdayHourClose", widget: "number"}
              - {label: "AM/PM", name: "thursdayHalfClose", widget: "select", options: ["AM", "PM"], default: ["PM"]}
        - label: "Friday Hours"
          name: "fridayHours"
          allow_add: false
          widget: "object"
          fields:
            - label: "Open"
              name: "fridayOpen"
              widget: "object"
              fields:
              - {label: "Hour", name: "fridayHourOpen", widget: "number"}
              - {label: "AM/PM", name: "fridayHalfOpen", widget: "select", options: ["AM", "PM"], default: ["AM"]}
            - label: "Close"
              name: "fridayClose"
              widget: "object"
              fields:
              - {label: "Hour", name: "fridayHourClose", widget: "number"}
              - {label: "AM/PM", name: "fridayHalfClose", widget: "select", options: ["AM", "PM"], default: ["PM"]}
        - label: "Saturday Hours"
          name: "saturdayHours"
          allow_add: false
          widget: "object"
          fields:
            - label: "Open"
              name: "saturdayOpen"
              widget: "object"
              fields:
              - {label: "Hour", name: "saturdayHourOpen", widget: "number"}
              - {label: "AM/PM", name: "saturdayHalfOpen", widget: "select", options: ["AM", "PM"], default: ["AM"]}
            - label: "Close"
              name: "saturdayClose"
              widget: "object"
              fields:
              - {label: "Hour", name: "saturdayHourClose", widget: "number"}
              - {label: "AM/PM", name: "saturdayHalfClose", widget: "select", options: ["AM", "PM"], default: ["PM"]}
        - label: "Sunday Hours"
          name: "sundayHours"
          allow_add: false
          widget: "object"
          fields:
            - label: "Open"
              name: "sundayOpen"
              widget: "object"
              fields:
              - {label: "Hour", name: "sundayHourOpen", widget: "number"}
              - {label: "AM/PM", name: "sundayHalfOpen", widget: "select", options: ["AM", "PM"], default: ["AM"]}
            - label: "Close"
              name: "sundayClose"
              widget: "object"
              fields:
              - {label: "Hour", name: "sundayHourClose", widget: "number"}
              - {label: "AM/PM", name: "sundayHalfClose", widget: "select", options: ["AM", "PM"], default: ["PM"]}